- name: Create auto.master and add map-files
  template:
    src: auto.master.j2
    dest: /etc/auto.master
  notify:
    - restart autofs

- name: Create map-files
  template:
    src: auto.mount.j2
    dest: "/etc/auto.{{item.name}}"
  with_dict: "{{ autofs_maps }}"
  notify:
    - restart autofs
